apiVersion: v1
kind: Namespace
metadata:
  name: my-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strap-deploy
  namespace: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strap
  template:
    metadata:
      labels:
        app: strap
    spec:
      containers:
      - name: strap
        image: strap
